"""M21 — LLM Tool Calls.

Provides the data types and ToolExecutor that allows the LLM to call
HearthNet capabilities mid-generation and inject the results back.

The actual LLM backends live in M04 (service.py); this module is the
orchestration layer that sits on top.
"""
from __future__ import annotations

import json
import uuid
from dataclasses import dataclass, field
from typing import Any, Callable, TYPE_CHECKING

if TYPE_CHECKING:  # pragma: no cover
    from hearthnet.bus.router import Router

# ---------------------------------------------------------------------------
# Data types
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ToolDefinition:
    """A tool the caller offers to the LLM.

    Translated by the LLM backend into its native tool format (e.g. the
    ``tools`` parameter accepted by Ollama, OpenAI, llama.cpp, etc.).
    """

    name: str
    """Short identifier visible to the LLM (must be ``[a-zA-Z0-9_-]``)."""

    description: str
    """Human-readable description; drives LLM tool selection."""

    parameters_schema: dict
    """JSON Schema object describing the ``arguments`` the LLM should pass."""

    bound_capability: str | None = None
    """If set, :class:`ToolExecutor` will dispatch via the bus using this cap."""

    bound_version: tuple[int, int] | None = None
    """Minimum version for the ``bound_capability``; ``None`` means any."""

    side_effects: bool = False
    """True if execution has side effects — affects retry semantics."""

    def to_openai_schema(self) -> dict:
        """Render as an OpenAI / Ollama ``tools`` entry."""
        return {
            "type": "function",
            "function": {
                "name": self.name,
                "description": self.description,
                "parameters": self.parameters_schema,
            },
        }


@dataclass(frozen=True)
class ToolCall:
    """A request from the LLM to execute a tool."""

    id: str
    """Opaque identifier generated by the LLM; echoed in :class:`ToolResult`."""

    name: str
    """Matches :attr:`ToolDefinition.name`."""

    arguments: dict
    """Deserialized JSON object; validated against the definition schema."""

    @classmethod
    def from_openai_delta(cls, delta: dict) -> "ToolCall":
        """Parse an OpenAI-style ``tool_calls[*]`` dict."""
        func = delta.get("function", {})
        raw_args = func.get("arguments", "{}")
        if isinstance(raw_args, str):
            try:
                args = json.loads(raw_args)
            except json.JSONDecodeError:
                args = {"_raw": raw_args}
        else:
            args = raw_args
        return cls(
            id=delta.get("id") or str(uuid.uuid4()),
            name=func.get("name", ""),
            arguments=args,
        )


@dataclass(frozen=True)
class ToolResult:
    """The result of executing a :class:`ToolCall`, fed back to the LLM."""

    tool_call_id: str
    """Must match :attr:`ToolCall.id`."""

    name: str
    """Matches :attr:`ToolCall.name`."""

    content: str | dict
    """Serialisable result; if dict it will be JSON-encoded before injection."""

    is_error: bool = False

    def to_message(self) -> dict:
        """Render as an OpenAI / Ollama ``tool`` role message."""
        body = (
            json.dumps(self.content) if isinstance(self.content, dict) else self.content
        )
        return {
            "role": "tool",
            "tool_call_id": self.tool_call_id,
            "name": self.name,
            "content": body,
        }


# ---------------------------------------------------------------------------
# ToolExecutor
# ---------------------------------------------------------------------------


class ToolExecutor:
    """Orchestrates the tool-call loop between the LLM and the bus.

    Usage::

        executor = ToolExecutor(bus=node.bus, tools=[my_tool])
        result = await executor.execute(tool_call)
    """

    def __init__(
        self,
        bus: "Router | None" = None,
        tools: list[ToolDefinition] | None = None,
        custom_handlers: dict[str, Callable[..., Any]] | None = None,
    ) -> None:
        self._bus = bus
        self._tools: dict[str, ToolDefinition] = {
            t.name: t for t in (tools or [])
        }
        self._custom: dict[str, Callable[..., Any]] = custom_handlers or {}

    # ------------------------------------------------------------------
    # Public helpers
    # ------------------------------------------------------------------

    def definitions(self) -> list[ToolDefinition]:
        return list(self._tools.values())

    def openai_schema(self) -> list[dict]:
        """Return all tools rendered as OpenAI ``tools`` array entries."""
        return [t.to_openai_schema() for t in self._tools.values()]

    async def execute(self, call: ToolCall) -> ToolResult:
        """Dispatch *call* and return a :class:`ToolResult`.

        Lookup order:
        1. ``custom_handlers[call.name]``  (sync or async callable)
        2. ``ToolDefinition.bound_capability`` dispatched via bus
        3. Fallback: error result
        """
        definition = self._tools.get(call.name)

        # 1. Custom handler
        if call.name in self._custom:
            handler = self._custom[call.name]
            try:
                import asyncio

                if asyncio.iscoroutinefunction(handler):
                    out = await handler(**call.arguments)
                else:
                    out = handler(**call.arguments)
                return ToolResult(
                    tool_call_id=call.id,
                    name=call.name,
                    content=out if isinstance(out, (str, dict)) else str(out),
                    is_error=False,
                )
            except Exception as exc:  # noqa: BLE001
                return ToolResult(
                    tool_call_id=call.id,
                    name=call.name,
                    content={"error": str(exc)},
                    is_error=True,
                )

        # 2. Bus-dispatched capability
        if definition and definition.bound_capability and self._bus is not None:
            try:
                from hearthnet.bus.router import RouteRequest

                req = RouteRequest(
                    capability=definition.bound_capability,
                    version_req=definition.bound_version or (1, 0),
                    body={"input": call.arguments},
                    caller="tool-executor",
                    trace_id=str(uuid.uuid4()),
                )
                resp = await self._bus.call(req)
                out = resp.get("output", resp)
                return ToolResult(
                    tool_call_id=call.id,
                    name=call.name,
                    content=out if isinstance(out, (str, dict)) else str(out),
                    is_error=False,
                )
            except Exception as exc:  # noqa: BLE001
                return ToolResult(
                    tool_call_id=call.id,
                    name=call.name,
                    content={"error": str(exc)},
                    is_error=True,
                )

        # 3. Fallback
        return ToolResult(
            tool_call_id=call.id,
            name=call.name,
            content={"error": f"No handler registered for tool '{call.name}'"},
            is_error=True,
        )

    async def run_loop(
        self,
        initial_messages: list[dict],
        max_rounds: int = 5,
    ) -> list[dict]:
        """Run a full tool-call loop and return the accumulated message list.

        Each round:
        1. Calls the LLM (not implemented here — caller provides messages so far)
        2. If the LLM response contains tool calls, executes them
        3. Appends tool results and continues

        This is a *stub* for the protocol loop — the actual LLM invocation
        happens in the LLM service (M04) which calls back via the bus.  This
        helper is used by the Gradio UI (M08) and tests.

        Returns the extended message list after all tool rounds are complete.
        """
        messages = list(initial_messages)
        for _ in range(max_rounds):
            # Check for pending tool calls in the last assistant message
            last = messages[-1] if messages else {}
            tool_calls_raw = last.get("tool_calls", [])
            if not tool_calls_raw:
                break
            # Execute each tool call
            tool_results = []
            for tc_raw in tool_calls_raw:
                tc = ToolCall.from_openai_delta(tc_raw)
                result = await self.execute(tc)
                tool_results.append(result)
                messages.append(result.to_message())
            # If all results are returned, no more rounds needed
            break
        return messages
